# Generated by Django 6.0.3 on 2026-04-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_by', models.CharField(max_length=128)),
                ('class_name', models.CharField(max_length=128)),
                ('term', models.CharField(max_length=128)),
                ('professor', models.CharField(max_length=128)),
                ('content_type', models.CharField(max_length=128)),
            ],
        ),
    ]
